<template>
  <Teleport to="body"><div class="schedule-overlay" @click.self="!busy && $emit('close')"><section class="schedule-dialog" role="dialog" aria-modal="true" aria-labelledby="schedule-title"><header><h2 id="schedule-title">Lịch khởi hành · {{ tour.Title }}</h2><button :disabled="busy" @click="$emit('close')">Đóng</button></header><p>Thêm lịch mới cho mỗi đợt. Ngày chuyến đi đã có booking được giữ nguyên.</p><p v-if="error" class="error" role="alert">{{ error }}</p><form @submit.prevent="create"><h3>Tạo lịch mới</h3><div class="fields"><label>Khởi hành (giờ Việt Nam)<input v-model="form.startDate" type="datetime-local" required :disabled="busy" /></label><label>Kết thúc (giờ Việt Nam)<input v-model="form.endDate" type="datetime-local" required :disabled="busy" /></label><label>Số chỗ tối đa<input v-model.number="form.maxSlots" type="number" min="1" required :disabled="busy" /></label></div><button :disabled="busy" class="primary">{{ busy ? 'Đang xử lý…' : 'Thêm lịch khởi hành' }}</button></form><p v-if="loading">Đang tải lịch…</p><div v-else class="rows"><article v-for="d in departures" :key="d.DepartureID"><strong>{{ date(d.StartDate) }} → {{ date(d.EndDate) }}</strong><p>{{ d.AvailableSlots }}/{{ d.MaxSlots }} chỗ trống · {{ d.Status === 'OPEN' ? 'Mở bán' : 'Đóng bán' }}</p><div class="fields"><label>Sức chứa<input v-model.number="d.newMax" type="number" min="1" :disabled="busy" /></label><button :disabled="busy" @click="update(d,{maxSlots:d.newMax})">Lưu sức chứa</button><button :disabled="busy" @click="update(d,{status:d.Status === 'OPEN' ? 'CLOSED' : 'OPEN'})">{{ d.Status === 'OPEN' ? 'Đóng bán' : 'Mở bán' }}</button></div></article><p v-if="!departures.length">Chưa có lịch khởi hành.</p></div></section></div></Teleport>
</template>
<script setup>
import { ref, onMounted } from 'vue';
import adminApi from '../services/api';
const props = defineProps({ tour:{type:Object,required:true} });const emit=defineEmits(['close','updated']);
const departures=ref([]),error=ref(''),busy=ref(false),loading=ref(true),form=ref({startDate:'',endDate:'',maxSlots:25});
const date=value=>value?new Date(value).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'}):'Chưa xác định';
async function load(){loading.value=true;try{const data=await adminApi.getDepartures(props.tour.TourID);departures.value=data.data.map(d=>({...d,newMax:d.MaxSlots}));}catch(e){error.value=e.message;}finally{loading.value=false;}}
async function create(){busy.value=true;error.value='';try{await adminApi.createDeparture(props.tour.TourID,form.value);form.value={startDate:'',endDate:'',maxSlots:25};await load();emit('updated');}catch(e){error.value=e.message;}finally{busy.value=false;}}
async function update(d,payload){busy.value=true;error.value='';try{await adminApi.updateDeparture(props.tour.TourID,d.DepartureID,payload);await load();emit('updated');}catch(e){error.value=e.message;}finally{busy.value=false;}}
onMounted(load);
</script>
<style scoped>
.schedule-overlay{position:fixed;inset:0;background:#0f172a99;display:flex;align-items:center;justify-content:center;z-index:3000;padding:20px}.schedule-dialog{background:white;color:#1e293b;border-radius:24px;padding:28px;width:850px;max-width:100%;max-height:90vh;overflow:auto}header,.fields{display:flex;gap:16px;align-items:center;flex-wrap:wrap}header{justify-content:space-between}label{display:flex;flex-direction:column;gap:6px}input,button{padding:10px;border:1px solid #cbd5e1;border-radius:8px;font:inherit}button{cursor:pointer;background:white}button:disabled{opacity:.5}form,article{padding:20px 0;border-bottom:1px solid #e2e8f0}p{margin:12px 0}.primary{background:#2563eb;color:white;margin-top:16px}.error{color:#b91c1c}
</style>
